# Generated by Django 5.0 on 2024-03-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_voted",
            field=models.BooleanField(default=False),
        ),
    ]
