# Generated by Django 5.0 on 2024-04-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0002_userprofile_has_voted"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="user",),
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                default="siva@gmail.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pass1",
            field=models.CharField(default="py", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(default="py", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="voter_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
