# Generated by Django 5.0 on 2024-03-30 10:33

import Candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Candidates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Electioncandidates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidateID", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=10,
                    ),
                ),
                ("education", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to=Candidates.models.filePath)),
                ("party_name", models.CharField(max_length=100)),
                (
                    "party_symbol",
                    models.ImageField(upload_to=Candidates.models.filePath),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("votes", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
